#!/bin/sh
if ! head -1 "$1" | grep -qE "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,50}" ; then
  echo "Invalid commit message format."
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}" ; then
  echo "Commit message is too long (maximum is 88 characters)."
  exit 1
fi